finish task 9.4
AdamPawlinski/java-script-9.4 pull request #1
Opened 2018-03-07 05:13 UTC by AdamPawlinski

finish task 9.4. ask for accept.

2018-03-09 00:45 UTC, matwjablonski requested changes

2018-03-09 00:45 UTC, matwjablonski commented on js/script.js
> +	for (k = height; k > i; k--){
where is declaration for `k`?

2018-03-09 21:15 UTC, AdamPawlinski commented
bug fixed. Asking for acceptance.

2018-03-12 09:51 UTC, matwjablonski approved these changes

2018-09-11 04:46 UTC, merged